language: go

branches:
  only:
    - master

matrix:
  include:
    - go: 1.7.x
    - go: 1.8.x
    - go: 1.9.x
      env: ALLOW_E2E=true

before_cache:
- rm -rf $GOPATH/src/

cache:
  directories:
    - $GOPATH/src
    - $GOPATH/pkg

install:
- go get github.com/gorilla/mux
- go get github.com/go-sql-driver/mysql
- go get golang.org/x/crypto/pbkdf2
- go build