language: go

go:
  - "1.8"
  - "1.9"
  - "1.10.x"
  - master

matrix:
  allow_failures:
    - go: master
    fast_finish: true
  notifications:
    email: false

  before_script:
    - GO_FILES=$(find . -iname '*.go' -type f)
    - go get github.com/gorilla/mux
    - go get github.com/go-sql-driver/mysql
    - go get golang.org/x/crypto/pbkdf2

  script:
  - go build