USE tux;

CREATE TABLE schema_migrations (
  version INT NOT NULL PRIMARY KEY
)
INSERT INTO schema_migrations (version) VALUES (1);

CREATE TABLE IF NOT EXISTS users (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(128) NOT NULL UNIQUE,
  password VARCHAR(256) NOT NULL,
  email VARCHAR(128) NOT NULL,
  token VARCHAR(256) NOT NULL,
  time_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status ENUM('new', 'activate', 'disabled') NOT NULL DEFAULT 'new',
  admin TINYINT(1) DEFAULT 0
);

CREATE TABLE IF NOT EXISTS api_keys (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  api_id VARCHAR(16) NOT NULL UNIQUE,
  api_key VARCHAR(128) NOT NULL,
  time_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  nonce BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS tux_config IF NOT EXISTS (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  setting_key VARCHAR(65),
  setting_value VARCHAR(256)
);